# -*- coding: utf-8 -*-
"""AutoScraper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b2oOz3ZZJAuE1p5F947bs0RCUaBUK7ju

# Install autoscraper library
"""

pip install autoscraper

"""# Load libraries"""

from autoscraper import AutoScraper
import pandas as pd

"""# Defining url and search word"""

search = "iphone+11+silver"
amazon_url="https://www.amazon.in/s?k={}&s=price-desc-rank".format(search)
print(amazon_url)

"""# Defining what data I want """

wanted_list=["https://m.media-amazon.com/images/I/71umuN8XVeL._AC_UY218_.jpg","New Apple iPhone 12 Pro Max (128GB) - Silver","1,25,900","501"]

"""# Creating scraper object"""

scraper=AutoScraper()
result=scraper.build(amazon_url,wanted_list)

"""# Finding similar data"""

data = scraper.get_result_similar(amazon_url,grouped=True)
print(data)

keys = list(data.keys())
print(keys)

"""# Defining alias"""

scraper.set_rule_aliases({str(keys[0]):'ImageUrl',str(keys[2]):'Title',str(keys[-2]):'Price',str(keys[-1]):'Reviews'})

scraper.save("amazon_in.json")

"""# Testing for other search word"""

amazon_scraper = AutoScraper()
amazon_scraper.load('amazon_in.json')

search = "samsung phones"
amazon_url="https://www.amazon.in/s?k={}&s=price-desc-rank".format(search)

data = amazon_scraper.get_result_similar(amazon_url, group_by_alias=True)
search_data = tuple(zip(data['Title'],data['ImageUrl'],data['Price'],data['Reviews']))

df = pd.DataFrame(columns=['Query','Title','Price','Reviews','ImageUrl'])
for i in range(len(search_data)):
    df.loc[len(df)] = [search,search_data[i][0],search_data[i][2],search_data[i][3],search_data[i][1]]

print(df.shape)
df

"""# [GitHub Link](https://github.com/abhashpanwar/autoscraper)

# [Deployment Link](https://abhash-autoscraper.herokuapp.com/)
"""

